package com.domain

const val STRING_EMPTY = ""
const val FLOAT_ZERO = 0f
const val INT_ZERO = 0

const val INT_NEGATIVE = -1

const val EXCEPTION_CODE_DEFAULT = 1000

const val PREFERENCES_SESSION = "PREFERENCES_SESSION"

const val EXCEPTION_CODE_BAD_REQUEST = 400
const val EXCEPTION_CODE_INTERNAL_SERVER = 500
const val EXCEPTION_USER_WRONG_CREDENTIALS = 403

const val APP_ID = "APP_BOOKAPP"
